openapi: 3.0.0
info:
  title: Aspire APIs
  description: Used For Practice
  version: 1.0.0
  contact:
    email: jayesh.berani@aspiresoftserv.com
servers:
  - url: http://localhost:8080/api
    description: Internal server for testing
paths:
  /auth/register:
    post:
      summary: Register user.
      tags:
        - User API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
          text/plain:
            schema:
              type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  User:
                    type: object
                    properties:                      
                      _id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      isAdmin:
                        type: boolean
                      createdAt:
                        type: string
                        format: date-time
                        example: '2017-07-21T17:32:28Z'
                      updatedAt:
                        type: string
                        format: date-time
                        example: '2017-07-21T17:32:28Z'
                      __v: 
                        type: number
  /auth/login:
    post:
      summary: Login user.
      tags:
        - User API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: Login successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  User:
                    type: object
                    properties:                      
                      _id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      isAdmin:
                        type: boolean
                      createdAt:
                        type: string
                        format: date-time
                        example: '2017-07-21T17:32:28Z'
                      updatedAt:
                        type: string
                        format: date-time
                        example: '2017-07-21T17:32:28Z'
                      __v: 
                        type: number
                  token:
                    type: string
